function main()
   local cHtml := ""

   cHtml += "<! DOCTYPE html>"
   cHtml += "<html lang='es'>"
   cHtml += "<head>"
   cHtml += "    <meta charset='UTF-8'>"
   cHtml += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
   cHtml += "    <title>AIOS 1.0</title>"
   cHtml += "    <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&family=JetBrains+Mono&display=swap' rel='stylesheet'>"
   cHtml += "    <style>"
   cHtml += "        :root {"
   cHtml += "            --bg: #0a0b10;"
   cHtml += "            --glass: rgba( 255, 255, 255, 0.05 );"
   cHtml += "            --glass-border: rgba( 255, 255, 255, 0.1 );"
   cHtml += "            --accent: linear-gradient( 135deg, #6366f1, #a855f7 );"
   cHtml += "            --text: #e2e8f0;"
   cHtml += "            --bot-bubble: rgba( 30, 41, 59, 0.7 );"
   cHtml += "            --user-bubble: linear-gradient( 135deg, #4f46e5, #7c3aed );"
   cHtml += "        }"
   cHtml += "        * { margin:0; padding:0; box-sizing: border-box; }"
   cHtml += "        body {"
   cHtml += "            font-family: 'Outfit', sans-serif;"
   cHtml += "            background: var( --bg );"
   cHtml += "            background-image: radial-gradient( circle at 20% 20%, rgba( 99, 102, 241, 0.15 ) 0%, transparent 40% ),"
   cHtml += "                              radial-gradient( circle at 80% 80%, rgba( 168, 85, 247, 0.15 ) 0%, transparent 40% );"
   cHtml += "            color: var( --text );"
   cHtml += "            height: 100vh;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            overflow: hidden;"
   cHtml += "        }"
   cHtml += "        header {"
   cHtml += "            padding: 1.5rem 2rem;"
   cHtml += "            background: var( --glass );"
   cHtml += "            backdrop-filter: blur( 10px );"
   cHtml += "            border-bottom: 1px solid var( --glass-border );"
   cHtml += "            display: flex;"
   cHtml += "            justify-content: space-between;"
   cHtml += "            align-items: center;"
   cHtml += "            z-index: 10;"
   cHtml += "        }"
   cHtml += "        header h1 { font-size: 1.5rem; font-weight: 600; letter-spacing: -0.5px; }"
   cHtml += "        .version-badge { background: var( --accent ); padding: 0.2rem 0.6rem; border-radius: 20px; font-size: 0.75rem; font-weight: bold; }"
   cHtml += "        .token-counter { font-size: 0.85rem; color: #a0aec0; display: flex; flex-direction: column; align-items: flex-end; }"
   cHtml += "        .token-counter span.price { font-weight: bold; color: #4ade80; }"
   cHtml += "        #chat-container {"
   cHtml += "            flex: 1;"
   cHtml += "            overflow-y: auto;"
   cHtml += "            padding: 2rem;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            gap: 1.5rem;"
   cHtml += "        }"
   cHtml += "        .message {"
   cHtml += "            max-width: 85%;"
   cHtml += "            padding: 1rem 1.25rem;"
   cHtml += "            border-radius: 1.2rem;"
   cHtml += "            line-height: 1.6;"
   cHtml += "            white-space: pre-wrap;"
   cHtml += "            animation: fadeIn 0.3s ease-out;"
   cHtml += "        }"
   cHtml += "        @keyframes fadeIn { from { opacity: 0; transform: translateY( 10px ); } to { opacity: 1; transform: translateY( 0 ); } }"
   cHtml += "        .user { align-self: flex-end; background: var( --user-bubble ); color: white; border-bottom-right-radius: 0.2rem; }"
   cHtml += "        .bot { align-self: flex-start; background: var( --bot-bubble ); backdrop-filter: blur( 5px ); border: 1px solid var( --glass-border ); border-bottom-left-radius: 0.2rem; }"
   cHtml += "        .error { align-self: center; background: rgba( 255,0,0,0.2 ); color: #ff8888; border: 1px solid #ff0000; padding: 0.5rem 1rem; border-radius: 10px; }"
   cHtml += "        pre { background: #1e1e1e; padding: 1rem; border-radius: 8px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; }"
   cHtml += "        img { max-width: 100%; height: auto; border-radius: 8px; margin-top: 0.5rem; }"
   cHtml += "        .input-wrapper { padding: 2rem; background: linear-gradient( to top, var( --bg ), transparent ); }"
   cHtml += "        .input-box {"
   cHtml += "            max-width: 900px; margin: 0 auto; background: var( --glass ); backdrop-filter: blur( 20px ); border: 1px solid var( --glass-border );"
   cHtml += "            border-radius: 1.5rem; padding: 0.5rem; display: flex; align-items: center; gap: 0.5rem;"
   cHtml += "        }"
   cHtml += "        input { flex: 1; background: transparent; border: none; color: white; padding: 0.75rem 1rem; font-size: 1rem; outline: none; }"
   cHtml += "        button { background: var( --accent ); border: none; color: white; padding: 0.75rem 1.5rem; border-radius: 1.1rem; font-weight: 600; cursor: pointer; }"
   cHtml += "        button:disabled { background: #444; }"
   cHtml += "        #mic-btn { background: transparent; padding: 0.5rem; font-size: 1.4rem; color: white; display: flex; align-items: center; justify-content: center; }"
   cHtml += "        #mic-btn.listening { color: #ef4444; animation: pulse_mic 1.5s infinite; }"
   cHtml += "        @keyframes pulse_mic { 0% { transform: scale(1); text-shadow: 0 0 0px transparent; } 50% { transform: scale(1.2); text-shadow: 0 0 10px #ef4444; } 100% { transform: scale(1); text-shadow: 0 0 0px transparent; } }"
   cHtml += "        .typing { display: flex; gap: 4px; padding: 10px; }"
   cHtml += "        .dot { width: 8px; height: 8px; background: #6366f1; border-radius: 50%; animation: bounce 1.4s infinite ease-in-out; }"
   cHtml += "        @keyframes bounce { 0%, 80%, 100% { transform: scale( 0 ); } 40% { transform: scale( 1 ); } }"
   cHtml += "        #voice-select option { background: #1e1e1e; color: #e2e8f0; }"
   cHtml += "    </style>"
   cHtml += "</head>"
   cHtml += "<body>"
   cHtml += "<header>"
   cHtml += "    <h1>AIOS</h1>"
   cHtml += "    <div style='display: flex; gap: 1rem; align-items: center;'>"
   cHtml += "        <select id='voice-select' style='background: var(--glass); color: white; border: 1px solid var(--glass-border); border-radius: 5px; padding: 0.2rem; outline: none; display: none; max-width: 250px;'></select>"
   cHtml += "        <div id='token-counter' class='token-counter'>Tokens: 0 <span class='price'>$0.0000</span></div>"
   cHtml += "        <button id='tts-btn' onclick='toggleTTS()' style='background:transparent; padding:0; font-size:1.5rem; outline:none; cursor:pointer;' title='Voz del Bot'>🔊</button>"
   cHtml += "        <button onclick='clearChat()'>Limpiar</button>"
   cHtml += "    </div>"
   cHtml += "</header>"
   cHtml += "<div id='chat-container'></div>"
   cHtml += "<div class='input-wrapper'>"
   cHtml += "    <div class='input-box'>"
   cHtml += "        <button id='mic-btn' onclick='toggleSpeech()' title='Hablar'>🎤</button>"
   cHtml += "        <input type='text' id='input' placeholder='Pregunta algo...' onkeydown='if( event.keyCode===13 ) sendMessage()'>"
   cHtml += "        <button id='send-btn' onclick='sendMessage()'>Enviar</button>"
   cHtml += "    </div>"
   cHtml += "</div>"
   cHtml += "<script>"
   cHtml += "    window.onerror = function( m, u, l ) { alert( 'Error: ' + m + ' en ' + l ); };"
   cHtml += "    var history_data = [];"
   cHtml += "    var total_tokens = 0;"
   cHtml += "    /* Gemini 1.5 Pro cost estimate: $1.25 per 1M prompt / $3.75 per 1M output approx -> simplified average $2.50 / 1M = $0.0000025 per token */"
   cHtml += "    var cost_per_token = 0.0000025;"
   cHtml += "    function addMessage( role, text ) {"
   cHtml += "        var container = document.getElementById( 'chat-container' );"
   cHtml += "        var div = document.createElement( 'div' );"
   cHtml += "        div.className = 'message ' + role;"
   cHtml += "        var formatted = text.replace( /&/g, '&amp;' ).replace( /</g, '&lt;' ).replace( />/g, '&gt;' );"
   cHtml += "        formatted = formatted.replace( /!\\[(.*?)\\]\\((.*?)\\)/g, '<img src=\"$2\" alt=\"$1\" />');"
   cHtml += "        formatted = formatted.split( '\\r\\n' ).join( '<br>' );"
   cHtml += "        formatted = formatted.split( '\\n' ).join( '<br>' );"
   cHtml += "        div.innerHTML = formatted;"
   cHtml += "        container.appendChild( div );"
   cHtml += "        setTimeout( function() { container.scrollTop = container.scrollHeight; }, 50 );"
   cHtml += "    }"
   cHtml += "    function addTyping() {"
   cHtml += "        var container = document.getElementById( 'chat-container' );"
   cHtml += "        var div = document.createElement( 'div' );"
   cHtml += "        div.id = 'typing-indicator';"
   cHtml += "        div.className = 'message bot typing';"
   cHtml += "        div.innerHTML = '⚙️ Pensando...';"
   cHtml += "        container.appendChild( div );"
   cHtml += "        container.scrollTop = container.scrollHeight;"
   cHtml += "    }"
   cHtml += "    function removeTyping() {"
   cHtml += "        var indicator = document.getElementById( 'typing-indicator' );"
   cHtml += "        if( indicator ) indicator.parentNode.removeChild( indicator );"
   cHtml += "    }"
   cHtml += "    function sendMessage() {"
   cHtml += "        var input = document.getElementById( 'input' );"
   cHtml += "        var text = input.value.trim();"
   cHtml += "        var btn = document.getElementById( 'send-btn' );"
   cHtml += "        if ( ! text ) return;"
   cHtml += "        addMessage( 'user', text );"
   cHtml += "        input.value = '';"
   cHtml += "        addTyping();"
   cHtml += "        btn.disabled = true;"
   cHtml += "        var params = 'query=' + encodeURIComponent( text );"
   cHtml += "        if ( history_data.length > 0 ) params += '&history=' + encodeURIComponent( JSON.stringify( history_data ) );"
   cHtml += "        console.log( 'SENDING:', params );"
   cHtml += "        var xhr = new XMLHttpRequest();"
   cHtml += "        xhr.open( 'POST', 'aios.prg', true );"
   cHtml += "        xhr.setRequestHeader( 'Content-type', 'application/x-www-form-urlencoded' );"
   cHtml += "        xhr.onreadystatechange = function() {"
   cHtml += "            if ( xhr.status !== 200 && xhr.status !== 0 ) { addMessage( 'error', 'Status: ' + xhr.status ); }"
   cHtml += "            if ( xhr.readyState == 4 ) {"
   cHtml += "                removeTyping(); btn.disabled = false;"
   cHtml += "                if ( xhr.status == 200 ) {"
   cHtml += "                    try {"
   cHtml += "                        var data = JSON.parse( xhr.responseText );"
   cHtml += "                        if ( data.success ) {"
   cHtml += "                            addMessage( 'bot', data.text );"
   cHtml += "                            speakText( data.text );"
   cHtml += "                            history_data.push( {role:'user', parts:[{text:text}]} );"
   cHtml += "                            history_data.push( {role:'model', parts:[{text:data.text}]} );"
   cHtml += "                            if ( data.usageMetadata && data.usageMetadata.totalTokenCount ) {"
   cHtml += "                                total_tokens += data.usageMetadata.totalTokenCount;"
   cHtml += "                                var cost = (total_tokens * cost_per_token).toFixed(4);"
   cHtml += "                                var spanCls = String.fromCharCode(34) + 'price' + String.fromCharCode(34);"
   cHtml += "                                var spanStrt = '<span class=' + spanCls + '>';"
   cHtml += "                                var spanEnd = '</span>';"
   cHtml += "                                document.getElementById('token-counter').innerHTML = 'Tokens: ' + total_tokens + ' ' + spanStrt + '$' + cost + spanEnd;"
   cHtml += "                            }"
   cHtml += "                            if ( typeof data.js_eval !== 'undefined' && data.js_eval !== '' ) {"
   cHtml += "                                setTimeout( function() {"
   cHtml += "                                    try {"
   cHtml += "                                        var executeJs = new Function( data.js_eval );"
   cHtml += "                                        executeJs();"
   cHtml += "                                    } catch(err) {"
   cHtml += "                                        console.error( 'JS Eval Error: ', err );"
   cHtml += "                                    }"
   cHtml += "                                }, 100 );"
   cHtml += "                            }"
   cHtml += "                        } else { addMessage( 'error', 'Error: ' + data.error ); }"
   cHtml += "                    } catch( e ) { addMessage( 'error', 'JSON Error: ' + xhr.responseText.substring( 0,100 ) ); }"
   cHtml += "                } else if( xhr.status !== 0 ) { addMessage( 'error', 'Server Error: ' + xhr.status ); }"
   cHtml += "            }"
   cHtml += "        };"
   cHtml += "        xhr.send( params );"
   cHtml += "    }"
   cHtml += "    function clearChat() {"
   cHtml += "        document.getElementById( 'chat-container' ).innerHTML = '';"
   cHtml += "        history_data = [];"
   cHtml += "        total_tokens = 0;"
   cHtml += "        document.getElementById('token-counter').innerHTML = 'Tokens: 0 <span class=' + String.fromCharCode(34) + 'price' + String.fromCharCode(34) + '>$0.0000</span>';"
   cHtml += "        if (window.speechSynthesis) window.speechSynthesis.cancel();"
   cHtml += "    }"
   cHtml += "    var ttsEnabled = true;"
   cHtml += "    var ttsVoices = [];"
   cHtml += "    function populateVoices() {"
   cHtml += "        if (!window.speechSynthesis) return;"
   cHtml += "        ttsVoices = window.speechSynthesis.getVoices();"
   cHtml += "        var voiceSelect = document.getElementById('voice-select');"
   cHtml += "        voiceSelect.innerHTML = '';"
   cHtml += "        var esVoices = ttsVoices.filter(function(v) { return v.lang.startsWith('es'); });"
   cHtml += "        if (esVoices.length > 0) {"
   cHtml += "            voiceSelect.style.display = 'block';"
   cHtml += "            esVoices.forEach(function(voice, index) {"
   cHtml += "                var option = document.createElement('option');"
   cHtml += "                option.textContent = voice.name + ' (' + voice.lang + ')';"
   cHtml += "                option.value = index;"
   cHtml += "                voiceSelect.appendChild(option);"
   cHtml += "            });"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    if (window.speechSynthesis) {"
   cHtml += "        populateVoices();"
   cHtml += "        if (speechSynthesis.onvoiceschanged !== undefined) {"
   cHtml += "            speechSynthesis.onvoiceschanged = populateVoices;"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    function toggleTTS() {"
   cHtml += "        ttsEnabled = !ttsEnabled;"
   cHtml += "        var btn = document.getElementById('tts-btn');"
   cHtml += "        var sel = document.getElementById('voice-select');"
   cHtml += "        if (ttsEnabled) { btn.innerHTML = '🔊'; btn.style.opacity = '1'; sel.style.opacity = '1'; } else { btn.innerHTML = '🔇'; btn.style.opacity = '0.5'; sel.style.opacity = '0.5'; if (window.speechSynthesis) window.speechSynthesis.cancel(); }"
   cHtml += "    }"
   cHtml += "    function speakText(text) {"
   cHtml += "        if (!ttsEnabled || !window.speechSynthesis) return;"
   cHtml += "        window.speechSynthesis.cancel();"
   cHtml += "        var cleanText = text.replace(/```[\\s\\S]*?```/g, 'bloque de código omitido').replace(/[*_#`]/g, '').replace(/<[^>]+>/g, '');"
   cHtml += "        var utterance = new SpeechSynthesisUtterance(cleanText);"
   cHtml += "        utterance.lang = 'es-ES';"
   cHtml += "        var voiceSelect = document.getElementById('voice-select');"
   cHtml += "        var esVoices = ttsVoices.filter(function(v) { return v.lang.startsWith('es'); });"
   cHtml += "        if (esVoices.length > 0 && voiceSelect.value !== '') {"
   cHtml += "            utterance.voice = esVoices[voiceSelect.value];"
   cHtml += "        }"
   cHtml += "        window.speechSynthesis.speak(utterance);"
   cHtml += "    }"
   cHtml += "    var SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;"
   cHtml += "    var recognition = null;"
   cHtml += "    var isListening = false;"
   cHtml += "    if (SpeechRecognition) {"
   cHtml += "        recognition = new SpeechRecognition();"
   cHtml += "        recognition.lang = 'es-ES';"
   cHtml += "        recognition.continuous = false;"
   cHtml += "        recognition.interimResults = false;"
   cHtml += "        recognition.onstart = function() {"
   cHtml += "            isListening = true;"
   cHtml += "            document.getElementById('mic-btn').classList.add('listening');"
   cHtml += "            document.getElementById('input').placeholder = 'Escuchando...';"
   cHtml += "        };"
   cHtml += "        recognition.onresult = function(event) {"
   cHtml += "            var transcript = event.results[0][0].transcript;"
   cHtml += "            document.getElementById('input').value = transcript;"
   cHtml += "            sendMessage();"
   cHtml += "        };"
   cHtml += "        recognition.onerror = function(event) {"
   cHtml += "            console.error('Error de voz:', event.error);"
   cHtml += "            if (event.error === 'not-allowed') alert('Permiso de micrófono denegado. Revisa la configuración de permisos.');"
   cHtml += "            stopListening();"
   cHtml += "        };"
   cHtml += "        recognition.onend = function() {"
   cHtml += "            stopListening();"
   cHtml += "        };"
   cHtml += "    } else {"
   cHtml += "        console.warn('Reconocimiento de voz no soportado.');"
   cHtml += "    }"
   cHtml += "    function toggleSpeech() {"
   cHtml += "        if (!recognition) {"
   cHtml += "            alert('API de voz no soportada en este navegador.');"
   cHtml += "            return;"
   cHtml += "        }"
   cHtml += "        if (isListening) {"
   cHtml += "            recognition.stop();"
   cHtml += "        } else {"
   cHtml += "            try {"
   cHtml += "                recognition.start();"
   cHtml += "            } catch (e) {"
   cHtml += "                console.error(e);"
   cHtml += "            }"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    function stopListening() {"
   cHtml += "        isListening = false;"
   cHtml += "        var btn = document.getElementById('mic-btn');"
   cHtml += "        if (btn) btn.classList.remove('listening');"
   cHtml += "        var inp = document.getElementById('input');"
   cHtml += "        if (inp) inp.placeholder = 'Pregunta algo...';"
   cHtml += "    }"
   cHtml += "</script>"
   cHtml += "</body></html>"

   UWrite( cHtml )
return ""

