function main()
   local cHtml := ""

   cHtml += "<! DOCTYPE html>"
   cHtml += "<html lang='es'>"
   cHtml += "<head>"
   cHtml += "    <meta charset='UTF-8'>"
   cHtml += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
   cHtml += "    <title>AIOS 1.0</title>"
   cHtml += "    <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&family=JetBrains+Mono&display=swap' rel='stylesheet'>"
   cHtml += "    <style>"
   cHtml += "        :root {"
   cHtml += "            --bg: #0a0b10;"
   cHtml += "            --glass: rgba( 255, 255, 255, 0.05 );"
   cHtml += "            --glass-border: rgba( 255, 255, 255, 0.1 );"
   cHtml += "            --accent: linear-gradient( 135deg, #6366f1, #a855f7 );"
   cHtml += "            --text: #e2e8f0;"
   cHtml += "            --bot-bubble: rgba( 30, 41, 59, 0.7 );"
   cHtml += "            --user-bubble: linear-gradient( 135deg, #4f46e5, #7c3aed );"
   cHtml += "        }"
   cHtml += "        * { margin:0; padding:0; box-sizing: border-box; }"
   cHtml += "        body {"
   cHtml += "            font-family: 'Outfit', sans-serif;"
   cHtml += "            background: var( --bg );"
   cHtml += "            background-image: radial-gradient( circle at 20% 20%, rgba( 99, 102, 241, 0.15 ) 0%, transparent 40% ),"
   cHtml += "                              radial-gradient( circle at 80% 80%, rgba( 168, 85, 247, 0.15 ) 0%, transparent 40% );"
   cHtml += "            color: var( --text );"
   cHtml += "            height: 100vh;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            overflow: hidden;"
   cHtml += "        }"
   cHtml += "        header {"
   cHtml += "            padding: 1.5rem 2rem;"
   cHtml += "            background: var( --glass );"
   cHtml += "            backdrop-filter: blur( 10px );"
   cHtml += "            border-bottom: 1px solid var( --glass-border );"
   cHtml += "            display: flex;"
   cHtml += "            justify-content: space-between;"
   cHtml += "            align-items: center;"
   cHtml += "            z-index: 10;"
   cHtml += "        }"
   cHtml += "        header h1 { font-size: 1.5rem; font-weight: 600; letter-spacing: -0.5px; }"
   cHtml += "        .version-badge { background: var( --accent ); padding: 0.2rem 0.6rem; border-radius: 20px; font-size: 0.75rem; font-weight: bold; }"
   cHtml += "        .token-counter { font-size: 0.85rem; color: #a0aec0; display: flex; flex-direction: column; align-items: flex-end; }"
   cHtml += "        .token-counter span.price { font-weight: bold; color: #4ade80; }"
   cHtml += "        #chat-container {"
   cHtml += "            flex: 1;"
   cHtml += "            overflow-y: auto;"
   cHtml += "            padding: 2rem;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            gap: 1.5rem;"
   cHtml += "        }"
   cHtml += "        .message {"
   cHtml += "            max-width: 85%;"
   cHtml += "            padding: 1rem 1.25rem;"
   cHtml += "            border-radius: 1.2rem;"
   cHtml += "            line-height: 1.6;"
   cHtml += "            white-space: pre-wrap;"
   cHtml += "            animation: fadeIn 0.3s ease-out;"
   cHtml += "        }"
   cHtml += "        @keyframes fadeIn { from { opacity: 0; transform: translateY( 10px ); } to { opacity: 1; transform: translateY( 0 ); } }"
   cHtml += "        .user { align-self: flex-end; background: var( --user-bubble ); color: white; border-bottom-right-radius: 0.2rem; }"
   cHtml += "        .bot { align-self: flex-start; background: var( --bot-bubble ); backdrop-filter: blur( 5px ); border: 1px solid var( --glass-border ); border-bottom-left-radius: 0.2rem; }"
   cHtml += "        .error { align-self: center; background: rgba( 255,0,0,0.2 ); color: #ff8888; border: 1px solid #ff0000; padding: 0.5rem 1rem; border-radius: 10px; }"
   cHtml += "        pre { background: #1e1e1e; padding: 1rem; border-radius: 8px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; }"
   cHtml += "        img { max-width: 100%; height: auto; border-radius: 8px; margin-top: 0.5rem; }"
   cHtml += "        .input-wrapper { padding: 2rem; background: linear-gradient( to top, var( --bg ), transparent ); }"
   cHtml += "        .input-box {"
   cHtml += "            max-width: 900px; margin: 0 auto; background: var( --glass ); backdrop-filter: blur( 20px ); border: 1px solid var( --glass-border );"
   cHtml += "            border-radius: 1.5rem; padding: 0.5rem; display: flex; align-items: center; gap: 0.5rem;"
   cHtml += "        }"
   cHtml += "        input { flex: 1; background: transparent; border: none; color: white; padding: 0.75rem 1rem; font-size: 1rem; outline: none; }"
   cHtml += "        button { background: var( --accent ); border: none; color: white; padding: 0.75rem 1.5rem; border-radius: 1.1rem; font-weight: 600; cursor: pointer; }"
   cHtml += "        button:disabled { background: #444; }"
   cHtml += "        #mic-btn { background: transparent; padding: 0.5rem; font-size: 1.4rem; color: white; display: flex; align-items: center; justify-content: center; }"
   cHtml += "        #mic-btn.listening { color: #ef4444; animation: pulse_mic 1.5s infinite; }"
   cHtml += "        @keyframes pulse_mic { 0% { transform: scale(1); text-shadow: 0 0 0px transparent; } 50% { transform: scale(1.2); text-shadow: 0 0 10px #ef4444; } 100% { transform: scale(1); text-shadow: 0 0 0px transparent; } }"
   cHtml += "        .typing { display: flex; gap: 4px; padding: 10px; }"
   cHtml += "        .dot { width: 8px; height: 8px; background: #6366f1; border-radius: 50%; animation: bounce 1.4s infinite ease-in-out; }"
   cHtml += "        @keyframes bounce { 0%, 80%, 100% { transform: scale( 0 ); } 40% { transform: scale( 1 ); } }"
   cHtml += "        #voice-select option { background: #1e1e1e; color: #e2e8f0; }"
   cHtml += "        .attachment-preview { font-size: 0.8rem; color: #4ade80; margin-top: 0.2rem; display: block; text-align: center; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 100px; }"
   cHtml += "        #sidebar { position: fixed; top: 0; left: -380px; width: 380px; height: 100vh; background: rgba(15,17,26,0.95); backdrop-filter: blur( 15px ); border-right: 1px solid var( --glass-border ); z-index: 100; transition: left 0.3s ease; display: flex; flex-direction: column; padding: 1.5rem; overflow-y: auto; box-shadow: 5px 0 15px rgba(0,0,0,0.5); }"
   cHtml += "        #sidebar.open { left: 0; }"
   cHtml += "        .sidebar-close { align-self: flex-end; background: transparent; border: none; color: white; font-size: 2rem; cursor: pointer; margin-bottom: 0.5rem; transition: color 0.2s; }"
   cHtml += "        .sidebar-close:hover { color: #ef4444; }"
   cHtml += "        .sidebar-section { margin-bottom: 1.5rem; animation: fadeIn 0.5s ease-out; }"
   cHtml += "        .sidebar-title { font-size: 1.2rem; font-weight: 600; color: #a855f7; margin-bottom: 0.8rem; border-bottom: 1px solid var( --glass-border ); padding-bottom: 0.4rem; display: flex; align-items: center; justify-content: space-between; }"
   cHtml += "        .sidebar-item { background: rgba(0,0,0,0.3); border-radius: 8px; padding: 1rem; margin-bottom: 0.6rem; border-left: 3px solid #6366f1; transition: transform 0.2s, background 0.2s; }"
   cHtml += "        .sidebar-item:hover { transform: translateX(5px); background: rgba(0,0,0,0.5); border-left-color: #a855f7; }"
   cHtml += "        .sidebar-item h4 { font-size: 0.95rem; margin-bottom: 0.4rem; color: #e2e8f0; font-weight: 600; }"
   cHtml += "        .sidebar-item p { font-size: 0.8rem; color: #a0aec0; line-height: 1.4; margin-bottom: 0.6rem; }"
   cHtml += "        .dna-badge { display: inline-block; background: #1e293b; color: #4ade80; font-size: 0.7rem; font-weight: 600; padding: 0.2rem 0.5rem; border-radius: 4px; border: 1px solid #334155; }"
   cHtml += "        #hamburger-btn { background: transparent; border: none; color: white; font-size: 1.8rem; cursor: pointer; margin-right: 1rem; transition: color 0.2s; }"
   cHtml += "        #hamburger-btn:hover { color: #a855f7; }"
   cHtml += "    </style>"
   cHtml += "</head>"
   cHtml += "<body>"
   cHtml += "<div id='sidebar'>"
   cHtml += "    <button class='sidebar-close' onclick='toggleSidebar()'>&times;</button>"
   cHtml += "    <div class='sidebar-section'><div class='sidebar-title'>1. Planificación</div>"
   cHtml += "        <div class='sidebar-item'><h4>1.1. Recepción y Memoria</h4><p>Recibe el prompt (vía Slack, Discord, Web o Terminal) y busca en su base de datos local interacciones pasadas del usuario.</p><span class='dna-badge'>OpenClaw</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>1.2. Análisis de Contexto (RAG)</h4><p>Escanea el repositorio de código, lee issues abiertos y revisa la documentación actual para entender el estado del proyecto.</p><span class='dna-badge'>DeepWiki / Agent Zero</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>1.3. Creación del Grafo de Tareas</h4><p>Divide el prompt en pasos lógicos secuenciales (Ej: 1. Leer archivo -&gt; 2. Escribir test -&gt; 3. Crear función -&gt; 4. Probar).</p><span class='dna-badge'>Devin</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>1.4. Intervención Humana (Opcional)</h4><p>Pausa y muestra la lista de tareas al usuario para que apruebe, modifique o cancele el plan antes de escribir una sola línea.</p><span class='dna-badge'>Devin / Agent Zero</span></div>"
   cHtml += "    </div>"
   cHtml += "    <div class='sidebar-section'><div class='sidebar-title'>2. Ejecución <span style='font-size:0.75rem; color:#a0aec0; font-weight:normal;'>(Bucle iterativo)</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>2.1. Preparación del Sandbox</h4><p>Inicia un contenedor aislado (Docker) con acceso a herramientas de OS, terminal y navegador para no romper tu sistema local.</p><span class='dna-badge'>Devin</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>2.2. Toma de Acción</h4><p>Lee la primera tarea pendiente y ejecuta el código, lanza comando en consola o busca en la web.</p><span class='dna-badge'>Agent Zero</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>2.3. Verificación de Errores</h4><p>Ejecuta el código creado. Si el compilador o los tests lanzan un error, lo lee y entiende qué falló.</p><span class='dna-badge'>Devin</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>2.4. Auto-corrección</h4><p>Corrige su propio código basándose en el error. No avanza a la siguiente tarea hasta que la actual funcione (o pide ayuda si se atasca).</p><span class='dna-badge'>Devin</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>2.5. Re-planificación Dinámica</h4><p>Si descubre que una tarea necesita pasos extra, añade sub-tareas a la lista original " + Chr(34) + "al vuelo" + Chr(34) + " y actualiza la UI.</p><span class='dna-badge'>Devin</span></div>"
   cHtml += "    </div>"
   cHtml += "    <div class='sidebar-section'><div class='sidebar-title'>3. Síntesis y Docs</div>"
   cHtml += "        <div class='sidebar-item'><h4>3.1. Resumen de Ejecución</h4><p>Escribe un resumen en lenguaje natural explicando qué hizo, qué archivos tocó y qué problemas resolvió (ideal para un Commit o PR).</p><span class='dna-badge'>Agent Zero</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>3.2. Actualización Docs-as-Code</h4><p>Edita los archivos Markdown de la wiki del proyecto, explicando el por qué de los cambios a nivel de negocio y arquitectura.</p><span class='dna-badge'>DeepWiki / CodeWiki</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>3.3. Generación de Diagramas</h4><p>Analiza dependencias de código y genera/actualiza gráficos de arquitectura usando código (como Mermaid.js).</p><span class='dna-badge'>DeepWiki / CodeWiki</span></div>"
   cHtml += "        <div class='sidebar-item'><h4>3.4. Consolidación de Memoria</h4><p>Guarda los errores encontrados y las soluciones aplicadas en memoria a largo plazo local para no cometer el mismo error mañana.</p><span class='dna-badge'>OpenClaw</span></div>"
   cHtml += "    </div>"
   cHtml += "</div>"
   cHtml += "<header>"
   cHtml += "    <div style='display:flex; align-items:center;'>"
   cHtml += "        <button id='hamburger-btn' onclick='toggleSidebar()'>☰</button>"
   cHtml += "        <h1>AIOS</h1>"
   cHtml += "    </div>"
   cHtml += "    <div style='display: flex; gap: 1rem; align-items: center;'>"
   cHtml += "        <select id='voice-select' style='background: var(--glass); color: white; border: 1px solid var(--glass-border); border-radius: 5px; padding: 0.2rem; outline: none; display: none; max-width: 250px;'></select>"
   cHtml += "        <div id='token-counter' class='token-counter'>Tokens: 0 <span class='price'>$0.0000</span></div>"
   cHtml += "        <button id='tts-btn' onclick='toggleTTS()' style='background:transparent; padding:0; font-size:1.5rem; outline:none; cursor:pointer;' title='Voz del Bot'>🔊</button>"
   cHtml += "        <button onclick='clearChat()'>Limpiar</button>"
   cHtml += "    </div>"
   cHtml += "</header>"
   cHtml += "<div id='chat-container'></div>"
   cHtml += "<div class='input-wrapper'>"
   cHtml += "    <div class='input-box'>"
   cHtml += "        <input type='file' id='file-upload' style='display: none;' onchange='handleFileSelect(event)'>"
   cHtml += "        <div style='display:flex; flex-direction:column; align-items:center;'>"
   cHtml += "           <button id='attach-btn' onclick='document.getElementById(" + Chr(34) + "file-upload" + Chr(34) + ").click()' title='Adjuntar archivo' style='background: transparent; padding: 0.5rem; font-size: 1.4rem; border:none; outline:none;'>📎</button>"
   cHtml += "           <span id='attach-name' class='attachment-preview'></span>"
   cHtml += "        </div>"
   cHtml += "        <button id='mic-btn' onclick='toggleSpeech()' title='Hablar'>🎤</button>"
   cHtml += "        <input type='text' id='input' placeholder='Pregunta algo...' onkeydown='if( event.keyCode===13 ) sendMessage()'>"
   cHtml += "        <button id='send-btn' onclick='sendMessage()'>Enviar</button>"
   cHtml += "    </div>"
   cHtml += "</div>"
   cHtml += "<script>"
   cHtml += "    function toggleSidebar() { document.getElementById('sidebar').classList.toggle('open'); }"
   cHtml += "    window.onerror = function( m, u, l ) { alert( 'Error: ' + m + ' en ' + l ); };"
   cHtml += "    var history_data = [];"
   cHtml += "    var total_tokens = 0;"
   cHtml += "    var current_attachment = null;"
   cHtml += "    /* Gemini 1.5 Pro cost estimate: $1.25 per 1M prompt / $3.75 per 1M output approx -> simplified average $2.50 / 1M = $0.0000025 per token */"
   cHtml += "    var cost_per_token = 0.0000025;"
   cHtml += "    function handleFileSelect(event) {"
   cHtml += "        var file = event.target.files[0];"
   cHtml += "        if (!file) return;"
   cHtml += "        current_attachment = file;"
   cHtml += "        document.getElementById('attach-name').textContent = file.name;"
   cHtml += "    }"
   cHtml += "    function addMessage( role, text ) {"
   cHtml += "        var container = document.getElementById( 'chat-container' );"
   cHtml += "        var div = document.createElement( 'div' );"
   cHtml += "        div.className = 'message ' + role;"
   cHtml += "        var formatted = text.replace( /&/g, '&amp;' ).replace( /</g, '&lt;' ).replace( />/g, '&gt;' );"
   cHtml += "        formatted = formatted.replace( /!" + Chr( 92 ) + "[(.*?)" + Chr( 92 ) + "]" + Chr( 92 ) + "((.*?)" + Chr( 92 ) + ")/g, '<img src=' + String.fromCharCode(34) + '$2' + String.fromCharCode(34) + ' alt=' + String.fromCharCode(34) + '$1' + String.fromCharCode(34) + ' />');"
   cHtml += "        formatted = formatted.split( '\\r\\n' ).join( '<br>' );"
   cHtml += "        formatted = formatted.split( '\\n' ).join( '<br>' );"
   cHtml += "        div.innerHTML = formatted;"
   cHtml += "        container.appendChild( div );"
   cHtml += "        setTimeout( function() { container.scrollTop = container.scrollHeight; }, 50 );"
   cHtml += "    }"
   cHtml += "    function addTyping() {"
   cHtml += "        var container = document.getElementById( 'chat-container' );"
   cHtml += "        var div = document.createElement( 'div' );"
   cHtml += "        div.id = 'typing-indicator';"
   cHtml += "        div.className = 'message bot typing';"
   cHtml += "        div.innerHTML = '⚙️ Pensando...';"
   cHtml += "        container.appendChild( div );"
   cHtml += "        container.scrollTop = container.scrollHeight;"
   cHtml += "    }"
   cHtml += "    function removeTyping() {"
   cHtml += "        var indicator = document.getElementById( 'typing-indicator' );"
   cHtml += "        if( indicator ) indicator.parentNode.removeChild( indicator );"
   cHtml += "    }"
   cHtml += "    async function sendMessage() {"
   cHtml += "        var input = document.getElementById( 'input' );"
   cHtml += "        var text = input.value.trim();"
   cHtml += "        var btn = document.getElementById( 'send-btn' );"
   cHtml += "        if ( ! text && ! current_attachment ) return;"
   cHtml += "        addMessage( 'user', text + (current_attachment ? '\\n[📎 ' + current_attachment.name + ']' : '') );"
   cHtml += "        input.value = '';"
   cHtml += "        addTyping();"
   cHtml += "        btn.disabled = true;"
   cHtml += "        var formData = new FormData();"
   cHtml += "        formData.append( 'query', text );"
   cHtml += "        if ( history_data.length > 0 ) formData.append( 'history', JSON.stringify( history_data ) );"
   cHtml += "        var url = 'aios.prg';"
   cHtml += "        if ( current_attachment ) {"
   cHtml += "            url = 'http://localhost:8080/';"
   cHtml += "            var base64Data = await new Promise((resolve) => {"
   cHtml += "                var reader = new FileReader();"
   cHtml += "                reader.onload = function(e) {"
   cHtml += "                    var ds = e.target.result;"
   cHtml += "                    resolve(ds.includes(',') ? ds.split(',')[1] : ds);"
   cHtml += "                };"
   cHtml += "                reader.readAsDataURL(current_attachment);"
   cHtml += "            });"
   cHtml += "            var attachObj = { name: current_attachment.name, type: current_attachment.type, data: base64Data };"
   cHtml += "            var blob = new Blob([JSON.stringify(attachObj)], { type: 'application/json' });"
   cHtml += "            formData.append('attachment', blob, current_attachment.name);"
   cHtml += "            document.getElementById('attach-name').textContent = '';"
   cHtml += "            document.getElementById('file-upload').value = '';"
   cHtml += "            current_attachment = null;"
   cHtml += "        }"
   cHtml += "        "
   cHtml += "        fetch( url, {"
   cHtml += "             method: 'POST',"
   cHtml += "             body: formData"
   cHtml += "        } )"
   cHtml += "        .then( response => {"
   cHtml += "            removeTyping(); btn.disabled = false;"
   cHtml += "            if ( !response.ok ) throw new Error( 'Server Error: ' + response.status );"
   cHtml += "            return response.json();"
   cHtml += "        })"
   cHtml += "        .then( data => {"
   cHtml += "            if ( data.success ) {"
   cHtml += "                 addMessage( 'bot', data.text );"
   cHtml += "                 speakText( data.text );"
   cHtml += "                 history_data.push( {role:'user', parts:[{text:text}]} );"
   cHtml += "                 history_data.push( {role:'model', parts:[{text:data.text}]} );"
   cHtml += "                 if ( data.usageMetadata && data.usageMetadata.totalTokenCount ) {"
   cHtml += "                     total_tokens += data.usageMetadata.totalTokenCount;"
   cHtml += "                     var cost = (total_tokens * cost_per_token).toFixed(4);"
   cHtml += "                     var spanCls = String.fromCharCode(34) + 'price' + String.fromCharCode(34);"
   cHtml += "                     var spanStrt = '<span class=' + spanCls + '>';"
   cHtml += "                     var spanEnd = '</span>';"
   cHtml += "                     document.getElementById('token-counter').innerHTML = 'Tokens: ' + total_tokens + ' ' + spanStrt + '$' + cost + spanEnd;"
   cHtml += "                 }"
   cHtml += "                 if ( typeof data.js_eval !== 'undefined' && data.js_eval !== '' ) {"
   cHtml += "                     setTimeout( function() {"
   cHtml += "                         try {"
   cHtml += "                             var executeJs = new Function( data.js_eval );"
   cHtml += "                             executeJs();"
   cHtml += "                         } catch(err) {"
   cHtml += "                             console.error( 'JS Eval Error: ', err );"
   cHtml += "                         }"
   cHtml += "                     }, 100 );"
   cHtml += "                 }"
   cHtml += "            } else {"
   cHtml += "                 addMessage( 'error', 'Error: ' + data.error );"
   cHtml += "            }"
   cHtml += "        })"
   cHtml += "        .catch( error => {"
   cHtml += "            console.error('Fetch Exception Detailed:', error);"
   cHtml += "            removeTyping(); btn.disabled = false;"
   cHtml += "            addMessage( 'error', 'Fetch Error: ' + error.message );"
   cHtml += "        });"
   cHtml += "    }"
   cHtml += "    function clearChat() {"
   cHtml += "        document.getElementById( 'chat-container' ).innerHTML = '';"
   cHtml += "        history_data = [];"
   cHtml += "        total_tokens = 0;"
   cHtml += "        document.getElementById('token-counter').innerHTML = 'Tokens: 0 <span class=' + String.fromCharCode(34) + 'price' + String.fromCharCode(34) + '>$0.0000</span>';"
   cHtml += "        if (window.speechSynthesis) window.speechSynthesis.cancel();"
   cHtml += "    }"
   cHtml += "    var ttsEnabled = true;"
   cHtml += "    var ttsVoices = [];"
   cHtml += "    function populateVoices() {"
   cHtml += "        if (!window.speechSynthesis) return;"
   cHtml += "        ttsVoices = window.speechSynthesis.getVoices();"
   cHtml += "        var voiceSelect = document.getElementById('voice-select');"
   cHtml += "        if (!voiceSelect || ttsVoices.length === 0) return;"
   cHtml += "        var currentVal = voiceSelect.value;"
   cHtml += "        voiceSelect.innerHTML = '';"
   cHtml += "        var esVoices = ttsVoices.filter(function(v) { return v.lang.startsWith('es'); });"
   cHtml += "        if (esVoices.length > 0) {"
   cHtml += "            voiceSelect.style.display = 'block';"
   cHtml += "            var defaultIndex = 0;"
   cHtml += "            esVoices.forEach(function(voice, index) {"
   cHtml += "                var option = document.createElement('option');"
   cHtml += "                option.textContent = voice.name + ' (' + voice.lang + ')';"
   cHtml += "                option.value = index;"
   cHtml += "                if (voice.name.indexOf('Estados Unidos') !== -1 || voice.lang === 'es-US') { defaultIndex = index; }"
   cHtml += "                voiceSelect.appendChild(option);"
   cHtml += "            });"
   cHtml += "            if (currentVal === '') {"
   cHtml += "                voiceSelect.selectedIndex = defaultIndex;"
   cHtml += "            } else {"
   cHtml += "                voiceSelect.value = currentVal;"
   cHtml += "            }"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    if (window.speechSynthesis) {"
   cHtml += "        populateVoices();"
   cHtml += "        if (speechSynthesis.onvoiceschanged !== undefined) {"
   cHtml += "            speechSynthesis.onvoiceschanged = populateVoices;"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    function toggleTTS() {"
   cHtml += "        ttsEnabled = !ttsEnabled;"
   cHtml += "        var btn = document.getElementById('tts-btn');"
   cHtml += "        var sel = document.getElementById('voice-select');"
   cHtml += "        if (ttsEnabled) { btn.innerHTML = '🔊'; btn.style.opacity = '1'; sel.style.opacity = '1'; } else { btn.innerHTML = '🔇'; btn.style.opacity = '0.5'; sel.style.opacity = '0.5'; if (window.speechSynthesis) window.speechSynthesis.cancel(); }"
   cHtml += "    }"
   cHtml += "    function speakText(text) {"
   cHtml += "        if (!ttsEnabled || !window.speechSynthesis) return;"
   cHtml += "        window.speechSynthesis.cancel();"
   cHtml += "        var cleanText = text.replace(/```[\\s\\S]*?```/g, 'bloque de código omitido');"
   cHtml += "        cleanText = cleanText.replace(/!" + Chr( 92 ) + "[.*?" + Chr( 92 ) + "]" + Chr( 92 ) + "(data:image.*?" + Chr( 92 ) + ")/g, ' [Imagen generada] ' );"
   cHtml += "        cleanText = cleanText.replace(/[*_#`]/g, '').replace(/<[^>]+>/g, '');"
   cHtml += "        var utterance = new SpeechSynthesisUtterance(cleanText);"
   cHtml += "        utterance.lang = 'es-ES';"
   cHtml += "        var voiceSelect = document.getElementById('voice-select');"
   cHtml += "        var esVoices = ttsVoices.filter(function(v) { return v.lang.startsWith('es'); });"
   cHtml += "        if (esVoices.length > 0 && voiceSelect.value !== '') {"
   cHtml += "            utterance.voice = esVoices[voiceSelect.value];"
   cHtml += "        }"
   cHtml += "        window.speechSynthesis.speak(utterance);"
   cHtml += "    }"
   cHtml += "    var SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;"
   cHtml += "    var recognition = null;"
   cHtml += "    var isListening = false;"
   cHtml += "    if (SpeechRecognition) {"
   cHtml += "        recognition = new SpeechRecognition();"
   cHtml += "        recognition.lang = 'es-ES';"
   cHtml += "        recognition.continuous = false;"
   cHtml += "        recognition.interimResults = false;"
   cHtml += "        recognition.onstart = function() {"
   cHtml += "            isListening = true;"
   cHtml += "            document.getElementById('mic-btn').classList.add('listening');"
   cHtml += "            document.getElementById('input').placeholder = 'Escuchando...';"
   cHtml += "        };"
   cHtml += "        recognition.onresult = function(event) {"
   cHtml += "            var transcript = event.results[0][0].transcript;"
   cHtml += "            document.getElementById('input').value = transcript;"
   cHtml += "            sendMessage();"
   cHtml += "        };"
   cHtml += "        recognition.onerror = function(event) {"
   cHtml += "            console.error('Error de voz:', event.error);"
   cHtml += "            if (event.error === 'not-allowed') alert('Permiso de micrófono denegado. Revisa la configuración de permisos.');"
   cHtml += "            stopListening();"
   cHtml += "        };"
   cHtml += "        recognition.onend = function() {"
   cHtml += "            stopListening();"
   cHtml += "        };"
   cHtml += "    } else {"
   cHtml += "        console.warn('Reconocimiento de voz no soportado.');"
   cHtml += "    }"
   cHtml += "    function toggleSpeech() {"
   cHtml += "        if (!recognition) {"
   cHtml += "            alert('API de voz no soportada en este navegador.');"
   cHtml += "            return;"
   cHtml += "        }"
   cHtml += "        if (isListening) {"
   cHtml += "            recognition.stop();"
   cHtml += "        } else {"
   cHtml += "            try {"
   cHtml += "                recognition.start();"
   cHtml += "            } catch (e) {"
   cHtml += "                console.error(e);"
   cHtml += "            }"
   cHtml += "        }"
   cHtml += "    }"
   cHtml += "    function stopListening() {"
   cHtml += "        isListening = false;"
   cHtml += "        var btn = document.getElementById('mic-btn');"
   cHtml += "        if (btn) btn.classList.remove('listening');"
   cHtml += "        var inp = document.getElementById('input');"
   cHtml += "        if (inp) inp.placeholder = 'Pregunta algo...';"
   cHtml += "    }"
   cHtml += "</script>"
   cHtml += "</body></html>"

   UWrite( cHtml )
return ""
