function main()
   local cHtml := ""

   cHtml += "<! DOCTYPE html>"
   cHtml += "<html lang='es'>"
   cHtml += "<head>"
   cHtml += "    <meta charset='UTF-8'>"
   cHtml += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
   cHtml += "    <title>AIOS 1.0</title>"
   cHtml += "    <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&family=JetBrains+Mono&display=swap' rel='stylesheet'>"
   cHtml += "    <style>"
   cHtml += "        :root {"
   cHtml += "            --bg: #0a0b10;"
   cHtml += "            --glass: rgba( 255, 255, 255, 0.05 );"
   cHtml += "            --glass-border: rgba( 255, 255, 255, 0.1 );"
   cHtml += "            --accent: linear-gradient( 135deg, #6366f1, #a855f7 );"
   cHtml += "            --text: #e2e8f0;"
   cHtml += "            --bot-bubble: rgba( 30, 41, 59, 0.7 );"
   cHtml += "            --user-bubble: linear-gradient( 135deg, #4f46e5, #7c3aed );"
   cHtml += "        }"
   cHtml += "        * { margin:0; padding:0; box-sizing: border-box; }"
   cHtml += "        body {"
   cHtml += "            font-family: 'Outfit', sans-serif;"
   cHtml += "            background: var( --bg );"
   cHtml += "            background-image: radial-gradient( circle at 20% 20%, rgba( 99, 102, 241, 0.15 ) 0%, transparent 40% ),"
   cHtml += "                              radial-gradient( circle at 80% 80%, rgba( 168, 85, 247, 0.15 ) 0%, transparent 40% );"
   cHtml += "            color: var( --text );"
   cHtml += "            height: 100vh;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            overflow: hidden;"
   cHtml += "            margin: 0;"
   cHtml += "        }"
   cHtml += "        #main-content {"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            height: 100vh;"
   cHtml += "            width: 100%;"
   cHtml += "            transition: margin-left 0.3s ease, width 0.3s ease;"
   cHtml += "        }"
   cHtml += "        #main-content.shifted {"
   cHtml += "            margin-left: 380px;"
   cHtml += "            width: calc(100% - 380px);"
   cHtml += "        }"
   cHtml += "        header {"
   cHtml += "            padding: 0.8rem 2rem;"
   cHtml += "            background: var( --glass );"
   cHtml += "            backdrop-filter: blur( 10px );"
   cHtml += "            border-bottom: 1px solid var( --glass-border );"
   cHtml += "            display: flex;"
   cHtml += "            justify-content: space-between;"
   cHtml += "            align-items: center;"
   cHtml += "            z-index: 10;"
   cHtml += "        }"
   cHtml += "        header h1 { font-size: 1.5rem; font-weight: 600; letter-spacing: -0.5px; }"
   cHtml += "        .version-badge { background: var( --accent ); padding: 0.2rem 0.6rem; border-radius: 20px; font-size: 0.75rem; font-weight: bold; }"
   cHtml += "        .token-counter { font-size: 0.85rem; color: #a0aec0; display: flex; flex-direction: column; align-items: flex-end; }"
   cHtml += "        .token-counter span.price { font-weight: bold; color: #4ade80; }"
   cHtml += "        #chat-container {"
   cHtml += "            flex: 1;"
   cHtml += "            overflow-y: auto;"
   cHtml += "            padding: 2rem;"
   cHtml += "            display: flex;"
   cHtml += "            flex-direction: column;"
   cHtml += "            gap: 1.5rem;"
   cHtml += "        }"
   cHtml += "        .message {"
   cHtml += "            max-width: 85%;"
   cHtml += "            padding: 1rem 1.25rem;"
   cHtml += "            border-radius: 1.2rem;"
   cHtml += "            line-height: 1.6;"
   cHtml += "            white-space: pre-wrap;"
   cHtml += "            animation: fadeIn 0.3s ease-out;"
   cHtml += "        }"
   cHtml += "        @keyframes fadeIn { from { opacity: 0; transform: translateY( 10px ); } to { opacity: 1; transform: translateY( 0 ); } }"
   cHtml += "        .user { align-self: flex-end; background: var( --user-bubble ); color: white; border-bottom-right-radius: 0.2rem; }"
   cHtml += "        .bot { align-self: flex-start; background: var( --bot-bubble ); backdrop-filter: blur( 5px ); border: 1px solid var( --glass-border ); border-bottom-left-radius: 0.2rem; }"
   cHtml += "        .error { align-self: center; background: rgba( 255,0,0,0.2 ); color: #ff8888; border: 1px solid #ff0000; padding: 0.5rem 1rem; border-radius: 10px; }"
   cHtml += "        pre { background: #1e1e1e; padding: 1rem; border-radius: 8px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; }"
   cHtml += "        img { max-width: 100%; height: auto; border-radius: 8px; margin-top: 0.5rem; }"
   cHtml += "        .input-wrapper { padding: 2rem; background: linear-gradient( to top, var( --bg ), transparent ); }"
   cHtml += "        .input-box {"
   cHtml += "            max-width: 900px; margin: 0 auto; background: var( --glass ); backdrop-filter: blur( 20px ); border: 1px solid var( --glass-border );"
   cHtml += "            border-radius: 1.5rem; padding: 0.5rem; display: flex; align-items: center; gap: 0.5rem;"
   cHtml += "        }"
   cHtml += "        input { flex: 1; background: transparent; border: none; color: white; padding: 0.75rem 1rem; font-size: 1rem; outline: none; }"
   cHtml += "        button { background: var( --accent ); border: none; color: white; padding: 0.75rem 1.5rem; border-radius: 1.1rem; font-weight: 600; cursor: pointer; }"
   cHtml += "        button:disabled { background: #444; }"
   cHtml += "        #mic-btn { background: transparent; padding: 0.5rem; font-size: 1.4rem; color: white; display: flex; align-items: center; justify-content: center; }"
   cHtml += "        #mic-btn.listening { color: #ef4444; animation: pulse_mic 1.5s infinite; }"
   cHtml += "        @keyframes pulse_mic { 0% { transform: scale(1); text-shadow: 0 0 0px transparent; } 50% { transform: scale(1.2); text-shadow: 0 0 10px #ef4444; } 100% { transform: scale(1); text-shadow: 0 0 0px transparent; } }"
   cHtml += "        .typing { display: flex; gap: 4px; padding: 10px; }"
   cHtml += "        .dot { width: 8px; height: 8px; background: #6366f1; border-radius: 50%; animation: bounce 1.4s infinite ease-in-out; }"
   cHtml += "        @keyframes bounce { 0%, 80%, 100% { transform: scale( 0 ); } 40% { transform: scale( 1 ); } }"
   cHtml += "        #voice-select option { background: #1e1e1e; color: #e2e8f0; }"
   cHtml += "        .attachment-preview { font-size: 0.8rem; color: #4ade80; margin-top: 0.2rem; display: block; text-align: center; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; max-width: 100px; }"
   cHtml += "        #sidebar { position: fixed; top: 0; left: -380px; width: 380px; height: 100vh; background: rgba(15,17,26,0.95); backdrop-filter: blur( 15px ); border-right: 1px solid var( --glass-border ); z-index: 100; transition: left 0.3s ease; display: flex; flex-direction: column; padding: 1.5rem; overflow-y: auto; overflow-x: hidden; resize: horizontal; min-width: 280px; max-width: 60vw; box-shadow: 5px 0 15px rgba(0,0,0,0.5); }"
   cHtml += "        #sidebar.open { left: 0; }"
   cHtml += "        .sidebar-close { align-self: flex-end; background: transparent; border: none; color: white; font-size: 2rem; cursor: pointer; margin-bottom: 0.5rem; transition: color 0.2s; }"
   cHtml += "        .sidebar-close:hover { color: #ef4444; }"
   cHtml += "        .sidebar-section { margin-bottom: 1.5rem; animation: fadeIn 0.5s ease-out; }"
   cHtml += "        .sidebar-title { font-size: 1.2rem; font-weight: 600; color: #a855f7; margin-bottom: 0.8rem; border-bottom: 1px solid var( --glass-border ); padding-bottom: 0.4rem; display: flex; align-items: center; justify-content: space-between; }"
   cHtml += "        .sidebar-item { background: rgba(0,0,0,0.3); border-radius: 8px; padding: 1rem; margin-bottom: 0.6rem; border-left: 3px solid #6366f1; transition: transform 0.2s, background 0.2s; }"
   cHtml += "        .sidebar-item:hover { transform: translateX(5px); background: rgba(0,0,0,0.5); border-left-color: #a855f7; }"
   cHtml += "        .sidebar-item h4 { font-size: 0.95rem; margin-bottom: 0.4rem; color: #e2e8f0; font-weight: 600; }"
   cHtml += "        .sidebar-item p { font-size: 0.8rem; color: #a0aec0; line-height: 1.4; margin-bottom: 0.6rem; }"
   cHtml += "        .dna-badge { display: inline-block; background: #1e293b; color: #4ade80; font-size: 0.7rem; font-weight: 600; padding: 0.2rem 0.5rem; border-radius: 4px; border: 1px solid #334155; }"
   cHtml += "        #hamburger-btn { background: transparent; border: none; color: white; font-size: 1.3rem; cursor: pointer; margin-right: 1rem; transition: color 0.2s; }"
   cHtml += "        #hamburger-btn:hover { color: #a855f7; }"
   cHtml += "        .context-menu { position: fixed; background: #1e293b; border: 1px solid #334155; border-radius: 6px; padding: 4px 0; min-width: 120px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.5); z-index: 1000; }"
   cHtml += "        .context-menu-item { padding: 8px 16px; color: #ef4444; cursor: pointer; font-size: 0.85rem; display: flex; align-items: center; gap: 8px; transition: background 0.2s; }"
   cHtml += "        .context-menu-item:hover { background: rgba(255, 255, 255, 0.05); }"
   cHtml += "    </style>"
   cHtml += "</head>"
   cHtml += "<body>"
   cHtml += "<div id='sidebar'>"
   cHtml += "    <button class='sidebar-close' onclick='toggleSidebar()'>&times;</button>"
   cHtml += "    <div class='sidebar-section'>"
   cHtml += "        <div class='sidebar-title'>Conversations</div>"
   cHtml += "        <div id='conversations-container'></div>"
   cHtml += "    </div>"
   cHtml += "    <div class='sidebar-section'>"
   cHtml += "        <div class='sidebar-title'>Tasks <span style='font-size:0.75rem; color:#a0aec0; font-weight:normal;' id='task-status-counter'></span></div>"
   cHtml += "        <div id='tasks-container'></div>"
   cHtml += "    </div>"
   cHtml += "</div>"
   cHtml += "<div id='main-content'>"
   cHtml += "<header>"
   cHtml += "    <div style='display:flex; align-items:center;'>"
   cHtml += "        <button id='hamburger-btn' onclick='toggleSidebar()'>☰</button>"
   cHtml += "        <h1>AIOS</h1>"
   cHtml += "    </div>"
   cHtml += "    <div style='display: flex; gap: 1rem; align-items: center;'>"
   cHtml += "        <select id='voice-select' style='background: var(--glass); color: white; border: 1px solid var(--glass-border); border-radius: 5px; padding: 0.2rem; outline: none; display: none; max-width: 250px;'></select>"
   cHtml += "        <div id='token-counter' class='token-counter'>Tokens: 0 <span class='price'>$0.0000</span></div>"
   cHtml += "        <button id='tts-btn' onclick='toggleTTS()' style='background:transparent; padding:0; font-size:1.5rem; outline:none; cursor:pointer;' title='Voz del Bot'>🔊</button>"
   cHtml += "        <button onclick='clearChat()'>Limpiar</button>"
   cHtml += "    </div>"
   cHtml += "</header>"
   cHtml += "<div id='chat-container'></div>"
   cHtml += "<div class='input-wrapper'>"
   cHtml += "    <div class='input-box'>"
   cHtml += "        <input type='file' id='file-upload' style='display: none;' onchange='handleFileSelect(event)'>"
   cHtml += "        <div style='display:flex; flex-direction:column; align-items:center;'>"
   cHtml += "           <button id='attach-btn' onclick='document.getElementById(" + Chr(34) + "file-upload" + Chr(34) + ").click()' title='Adjuntar archivo' style='background: transparent; padding: 0.5rem; font-size: 1.4rem; border:none; outline:none;'>📎</button>"
   cHtml += "           <span id='attach-name' class='attachment-preview'></span>"
   cHtml += "        </div>"
   cHtml += "        <button id='mic-btn' onclick='toggleSpeech()' title='Hablar'>🎤</button>"
   cHtml += "        <input type='text' id='input' placeholder='Pregunta algo...' onkeydown='if( event.keyCode===13 ) sendMessage()'>"
   cHtml += "        <button id='send-btn' onclick='sendMessage()'>Enviar</button>"
   cHtml += "    </div>"
   cHtml += "</div>"
   cHtml += "</div>" // end of main-content
   cHtml += "<script>" + Chr(13) + Chr(10) + hb_MemoRead( hb_DirBase() + "chat_script.js" ) + Chr(13) + Chr(10) + "</script>"
   cHtml += "</body></html>"

   UWrite( cHtml )
return ""
